---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/personal-library
  become: true

- name: Enable site
  file:
    src: /etc/nginx/sites-available/personal-library
    dest: /etc/nginx/sites-enabled/personal-library
    state: link
  become: true

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Test nginx configuration
  ansible.builtin.shell: nginx -t
  become: true

- name: Start and enable nginx
  systemd:
    name: nginx
    enabled: true
    state: restarted
  become: true